services:
  monitor:
    build: 
     context: ./app
     dockerfile: Dockerfile.prod
    image: ghcr.io/shesselink81/unifi-ai:v${VERSION}
    user: "1000:1000"
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      UNIFI_LOCAL_URL: https://${UNIFI_LOCAL_IP}/proxy/network
      UNIFI_LOCAL_API_KEY: ${UNIFI_LOCAL_API_KEY}
      UNIFI_CLOUD_URL: https://api.ui.com
      UNIFI_CLOUD_API_KEY: ${UNIFI_CLOUD_API_KEY}
