{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "live-home-page.dbFullname" . }}
  labels:
    {{- include "live-home-page.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.storage.storageClassName }}
  storageClassName: {{ .Values.db.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
{{- end }}
