{{- if not .Values.unifi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-ai.fullname" . }}
  labels:
    {{- include "unifi-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  local-api-key: {{ .Values.unifi.localApiKey | quote }}
  cloud-api-key: {{ .Values.unifi.cloudApiKey | quote }}
  {{- if .Values.unifi.dashboardToken }}
  dashboard-token: {{ .Values.unifi.dashboardToken | quote }}
  {{- end }}
{{- end }}
